db:
  image: postgres
  ports:
    - "5432"
 
redis:
  image: redis
  ports:
    - "6379"
 
web:
  build: .
  command: sudo bundle exec rails s -p 3000
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
  links:
    - db

